name: aggiorna RSS ordinanze COVID-19 Regione Siciliana

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '5 */4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: crea cartella utente bin, copia dentro l'eseguibile di miller, installa yq e xmlstarlet
      run: |-
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cp bin/scrape ~/bin
        cd ~/bin
        chmod +x mlr
        chmod +x scrape
        sudo pip install yq
        sudo apt-get install xmlstarlet
    - name: aggiorna RSS
      run: |-
        export PATH=$PATH:~/bin
        cd ./script/ordinanzeCovidRegioneSiciliana
        chmod +x ./ordinanzeCovidRegioneSiciliana.sh
        ./ordinanzeCovidRegioneSiciliana.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "ordinanzeCovidRegioneSiciliana: ${timestamp}" || exit 0
        git push
